repo: Revamp blog
+ Docker first.
+ Fix brain.

diff --git a/bin/animascii2ant b/bin/animascii2ant
--- a/bin/animascii2ant
+++ b/bin/animascii2ant
@@ -7,12 +7,12 @@
 # this script is expected to be run with just the animascii URL. It is
 # guaranteed to fail if you pass -a or -p.
 
-cd "$(dirname $0)"  # change to same directory as this script
+cd "$(dirname "$0")" || exit 1  # change to same directory as this script
 
 frame_sizes="$(./animascii2ant.py "$@" -p 2>&1 1>/dev/null)"
 
 if [ ! $? ]; then
-    echo "init::error() : failed to run animascii-to-ant.py with given args."
+    echo "error: $0: Failed to run animascii-to-ant.py with given args."
     exit 1
 fi
 
diff --git a/bin/compress-assets b/bin/compress-assets
--- a/bin/compress-assets
+++ b/bin/compress-assets
@@ -56,12 +56,12 @@ else
 fi
 '
 
-if [ ! -d $bin_path ]; then
-    echo "compress-assets:warning() : destination path for build not found: $bin_path" >&2
+if [ ! -d "$bin_path" ]; then
+    echo "warning: $0: destination path for build not found: $bin_path" >&2
     exit 0 # 0 because a directory which doesn't exist... already has all it's assets compressed
 fi
 
-pushd $bin_path >/dev/null
+pushd "$bin_path" >/dev/null
 find . -type f -regextype egrep -not -empty -iregex '.*\.(htm|html|txt|text|js|css)$' -print0 |
     if [ $silent -eq 0 ]; then
         xargs -r0 -I! bash -c "$verbose_install_script"
